<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BlazePisonet.SoftTimer.Watchdog</AssemblyName>
    <RootNamespace>BlazePisonet.SoftTimer.Watchdog</RootNamespace>
    <Version>0.3.0</Version>
    <FileVersion>0.3.0.0</FileVersion>
    <AssemblyVersion>0.3.0.0</AssemblyVersion>
  </PropertyGroup>
</Project>
